# People {.unnumbered}

### NHS Grampian Networked Data Lab Team
Jessica Butler, Lead Data Scientist  
Frank Popham, Senior Data Scientist  
Corri Black, STAT lead and Consultant in Public Health  

### University of Aberdeen Networked Data Lab Team
Raul Berrocal-Martin, Research Fellow    
Sharon Gordon, Coordinator  
New Hire, Lead, Grampian Data Safe Haven  
Bernhard Scheliga, Analyst, Grampian Data Safe Haven  
Will Ball, Research Fellow, now at Robert Gordon University  
Dimitra Blana, Lecturer  
Irmina Zborowska, Project Administrator and Impact Officer

### Health Foundation Team
Charles Tallack, Director of Data Analytics  
Kathryn Marszalek, Senior Analytical Manager  
Hannah Knight, Senior Analytical Manager  
Caroline Fraser, Analyst  
Tom Prendergast, Analyst  
Cham Kifetew, Program Manager  
Zoe Ruziczka, Programme Officer 

### Health Intelligence Collaborators
Jillian Evans, Head of Health Intelligence  
Craig Paterson  
Elaine Thompson   
Adam Gatcombe  
Richard Slessor  
Greg Cook  
Payal Narula  

### Aberdeen City Council Collaborators
Martin Murchie, Chief Officer (Data and Insights)  
Caroline Anderson, Information and Data Manager  
Helen Cannings, Project Manager / Governance 

### Aberdeenshire Collaborators
Tom Fensome